frase = '   Curso em Vídeo Python   '
print(frase)
print(frase[6])
print(frase[6:15])
print(frase[:15])
print(frase[15:])
print(frase[3:15:2])
print(frase[2::2])
print(frase[::2])
print(frase.count('O'))
print(frase.upper().count('O'))
print(len(frase))
print(len(frase.strip()))
print(frase.replace('Python', 'Lader'))
print('Curso' in frase)
print('Lader' in frase)
print(frase.find('Vídeo'))
print(frase.find('video'))
list = frase.split()
print(list)
print(list[0])
print(list[2][3])
