n = input('Digite algo: ')
print(n)
print(type(n))
print('É numérico? ', n.isnumeric())
print('É alfanumérico? ', n.isalnum())
print('É alfabético? ', n.isalpha())
print('É decimal? ', n.isdecimal())
print('É identificador? ', n.isidentifier())
print('É imprimível? ', n.isprintable())
print('É um espaço? ', n.isspace())
print('É um título? ', n.istitle())
print('É maiúsculo? ', n.isupper())
print('É minúsculo? ', n.islower())
