n = int(input('Taboada do: '))
print('{} x 0 = {}'.format(n, n*0))
print('{} x 1 = {}'.format(n, n*1))
print('{} x 2 = {}'.format(n, n*2))
print('{} x 3 = {}'.format(n, n*3))
print('{} x 4 = {}'.format(n, n*4))
print('{} x 5 = {}'.format(n, n*5))
print('{} x 6 = {}'.format(n, n*6))
print('{} x 7 = {}'.format(n, n*7))
print('{} x 8 = {}'.format(n, n*8))
print('{} x 9 = {}'.format(n, n*9))
print('{} x 10 = {}'.format(n, n*10))
print('-'*30)
print('{} x 0 = {} \n{} x 1 = {} \n{} x 2 = {} \n{} x 3 = {} \n{} x 4 = {} \n{} x 5 = {} \n{} x 6 = {} \n{} x 7 = {} '
      '\n{} x 8 = {} \n{} x 9 = {} \n{} x 10 = {}'.format(n, 0, n, n, n, n*2, n, n*3, n, n*4, n, n*5, n, n*6, n, n*7,
                                                          n, n*8, n, n*9, n, n*10))
