nome = str(input('Digite o seu nome: ')).strip()
print('Normal:', nome)
print('Maiúscula:', nome.upper())
print('Minúscula:', nome.lower())
print('Qtd caracteres(inclue espaços): {}.'.format(len(nome)))
# list = nome.split()
# Qtdlet = len(list[0]) + len(list[1]) + len(list[2]) + len(list[3]) + len(list[4])
# print('Qtd letras(não inclue espaços: {}.'.format(Qtdlet))
print('Qtd letras(não inclue espaços): {}'.format(len(nome)-nome.count(' ')))
# print('Qtd letras prim nome: {}.'.format(len(list[0])))
print('Qtd letras primeiro nome: {}'.format(nome.find(' ')))
