n = float(input('Digite um valor em metros(m): '))
print('em Kiômetros: {}Km'.format(n/1000))
print('Em Hectômetros: {}Hm'.format(n/100))
print('Em Decâmetros: {}Dam'.format(n/10))
print('Em decímetros: {:.2f}dm'.format(n*10))
print('Em centímetros: {:.2f}cm'.format(n*100))
print('Em milímetros: {:.2f}mm'.format(n*1000))
