a = input("Digite algo: ")
print('Tipo primitivo:', type(a))
print('É um valor numérico?', a.isnumeric())
print('É um valor alfabético?', a.isalpha())
print('É um valor alfanumérico?', a.isalnum())
print('É maiúsculo?', a.isupper())
print('É minúsculo?', a.islower())
print('É capitalizado?', a.istitle())
print('É um espaço?', a.isspace())
print('É imprimível?', a.isprintable())
